- name: Hello World
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

- name: Ping and List
  hosts: ayushservers
  tasks:
    - name: Ping
      ping:
    - name: list
      command: ls -lart 
      register: myoutput
    - set_fact:
        myoutput={{ myoutput.stdout }}
    - debug: var=myoutput
      run_once: true
