- name: Ping and List
  hosts: ayushservers
  tasks:
    - name: Hello Message
      ping:
    - name: list
      command: uname 
      register: myoutput
    - set_fact:
        myoutput={{ myoutput.stdout }}
    - debug: var=myoutput
      run_once: true
